-- +goose Up
CREATE TABLE `cluster` (
  id INT NOT NULL AUTO_INCREMENT,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vpc` (
  id INT NOT NULL AUTO_INCREMENT,
  cluster_id INT NOT NULL,
  external_id VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `igw` (
  id INT NOT NULL AUTO_INCREMENT,
  cluster_id INT NOT NULL,
  external_id VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `subnet` (
  id INT NOT NULL AUTO_INCREMENT,
  cluster_id INT NOT NULL,
  external_id VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rtb` (
  id INT NOT NULL AUTO_INCREMENT,
  cluster_id INT NOT NULL,
  subnet_id INT NULL,
  external_id VARCHAR(50) NOT NULL,
  association_id VARCHAR(50) NULL,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `security_group` (
  id INT NOT NULL AUTO_INCREMENT,
  cluster_id INT NOT NULL,
  kind VARCHAR(50) NOT NULL,
  external_id VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `instance` (
  id INT NOT NULL AUTO_INCREMENT,
  cluster_id INT NOT NULL,
  external_id VARCHAR(50) NOT NULL,
  public_ip VARCHAR(50) NULL,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
